version: "3.9"

services:
  client:
    image: hicsail/aida-chatbot-client:staging
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3022:80
    depends_on:
      - server
    networks:
      - app-network

  server:
    image: hicsail/aida-chatbot-server:staging
    build:
      context: ./servers/chatbot
      dockerfile: Dockerfile
    networks:
      - app-network

  # visualization:
  #   image: hicsail/aida-visualization:staging
  #   platform: linux/amd64
  #   build:
  #     context: ./servers/visualization
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3023:8092
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
