version: "3.9"

services:
  frontend:
    image: hicsail/aida-client:staging
    build: ./client
    ports:
      - 3022:80
    depends_on:
      - server
      - db-api
    networks:
      - app-network

  backend-chatbot:
    image: hicsail/aida-chatbot-server:staging
    build: ./servers/chatbot
    networks:
      - app-network

  backend-digital-repo:
    image: hicsail/aida-db-api:staging
    build: ./servers/db-api
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

  visualization:
    image: hicsail/aida-visualization:staging
    build: ./servers/visualization
    ports:
      - 3023:8092
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
