version: "3.9"
services:
  frontend:
    build:
      context: ./client
      args:
        - VITE_CHATBOT_URL=$VITE_CHATBOT_URL
        - VITE_DB_API_URL=$VITE_DB_API_URL
        - VITE_MODEL_URL=$VITE_MODEL_URL
    ports:
      - 3000:80
    depends_on:
      - backend-chatbot
      - backend-digital-repo
      - visualization
    networks:
      - app-network

  backend-chatbot:
    build: ./servers/chatbot
    networks:
      - app-network
    env_file:
      - ./servers/chatbot/.env

  backend-digital-repo:
    build: ./servers/db-api
    depends_on:
      - mongodb
    networks:
      - app-network
    env_file:
      - ./servers/db-api/.env

  mongodb:
    image: mongo:6
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

  visualization:
    build: ./servers/visualization
    ports:
      - 3001:8092
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
