version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - server
    networks:
      - app-network
    env_file:
      - ./client/.env

  server:
    build:
      context: ./servers/chatbot
      dockerfile: Dockerfile
    networks:
      - app-network
    env_file:
      - ./servers/chatbot/.env

  visualization:
    build:
      context: ./servers/visualization
      dockerfile: Dockerfile
    ports:
      - 3001:8092
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
