version: "3.9"

services:
  frontend:
    image: hicsail/aida-frontend:[VERSION]
    ports:
      - 3022:80
    depends_on:
      - backend-digital-repo
      - visualization
    networks:
      - app-network

  backend-digital-repo:
    image: hicsail/aida-backend-digital-repo:[VERSION]
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

  visualization:
    image: hicsail/aida-visualization:[VERSION]
    ports:
      - 3023:5001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
