version: "3.9"
services:
  client:
    build:
      context: ./client
      args:
        - VITE_CHATBOT_URL=$VITE_CHATBOT_URL
        - VITE_DB_API_URL=$VITE_DB_API_URL
    ports:
      - 3000:80
    depends_on:
      - server
      - db-api
    networks:
      - app-network

  server:
    build: ./servers/chatbot
    networks:
      - app-network
    env_file:
      - ./servers/chatbot/.env

  db-api:
    build: ./servers/db-api
    depends_on:
      - mongodb
    networks:
      - app-network
    env_file:
      - ./servers/db-api/.env

  mongodb:
    image: mongo:6
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

  visualization:
    build: ./servers/visualization
    ports:
      - 3001:8092
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
