version: "3.9"

services:
  client:
    image: hicsail/aida-chatbot-client:staging
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - server
    networks:
      - app-network

  server:
    image: hicsail/aida-chatbot-server:staging
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
