name: server
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  chatbot-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Staging Build
        uses: docker/build-push-action@v5
        with:
          context: ./servers/chatbot
          push: ${{ github.event_name != 'pull_request' }}
          tags: hicsail/aida-chatbot-server:staging
          build-args: |
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

  chatbot-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Staging Build
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: ${{ github.event_name != 'pull_request' }}
          tags: hicsail/aida-chatbot-client:staging
          build-args: |
            VITE_CHATBOT_URL=${{ secrets.VITE_CHATBOT_URL }}

  visualization:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Staging Build
        uses: docker/build-push-action@v5
        with:
          context: ./servers/visualization
          push: ${{ github.event_name != 'pull_request' }}
          tags: hicsail/aida-visualization:staging
