name: server
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  backend-digital-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Image Tag
        id: set_tag
        run: echo "IMAGE_TAG=${{ github.ref_type == 'tag' && github.ref_name || 'staging' }}" >> $GITHUB_ENV

      - name: Build & Push Docker Staging Build
        uses: docker/build-push-action@v5
        with:
          context: ./servers/db-api
          push: ${{ github.event_name != 'pull_request' }}
          tags: hicsail/aida-backend-digital-repo:${{ env.IMAGE_TAG }}
          build-args: |
            MONGO_URI=${{ github.ref_type == 'tag' && secrets.MONGO_URI || secrets.MONGO_URI_STAGING }}

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Image Tag
        id: set_tag
        run: echo "IMAGE_TAG=${{ github.ref_type == 'tag' && github.ref_name || 'staging' }}" >> $GITHUB_ENV

      - name: Build & Push Docker Staging Build
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: ${{ github.event_name != 'pull_request' }}
          tags: hicsail/aida-frontend:${{ env.IMAGE_TAG }}
          build-args: |
            VITE_DB_API_URL=${{  github.ref_type == 'tag' && secrets.VITE_DB_API_URL || secrets.VITE_DB_API_URL_STAGING }}
            VITE_MODEL_URL=${{  github.ref_type == 'tag' && secrets.VITE_MODEL_URL || secrets.VITE_MODEL_URL_STAGING }}

  visualization:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Image Tag
        id: set_tag
        run: echo "IMAGE_TAG=${{ github.ref_type == 'tag' && github.ref_name || 'staging' }}" >> $GITHUB_ENV

      - name: Build & Push Docker Staging Build
        uses: docker/build-push-action@v5
        with:
          context: ./servers/visualization
          push: ${{ github.event_name != 'pull_request' }}
          tags: hicsail/aida-visualization:${{ env.IMAGE_TAG }}

  deployment:
    run-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [backend-digital-repo, frontend, visualization]
    steps:
      - name: Push to Staging
        uses: fjogeleit/http-request-action@v1
        with:
          method: POST
          url: ${{ secrets.PORTAINER_WEBHOOK }}
          preventFailureOnNoResponse: true
